# Generated by Django 5.0.6 on 2024-09-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_re_attempt_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
