# Generated by Django 5.0.6 on 2024-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='Conatct No:', max_length=12),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='mobile_number',
            field=models.CharField(default='Mobile No.', max_length=12),
        ),
    ]
